# Generated by Django 5.0.3 on 2024-04-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('Brand', models.CharField(blank=True, max_length=200, null=True)),
                ('SubCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('about_product', models.TextField(blank=True, null=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
