# Generated by Django 5.0.3 on 2024-04-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
