# Generated by Django 5.0.3 on 2024-04-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ImageURl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
