# Generated by Django 5.0.3 on 2024-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_answer_question_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
