# Generated by Django 5.0.3 on 2024-04-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
